### ISSUE TITLE
[solved] - [no text] when org-annotate-display-notes

### ISSUE THREAD

**Issue by samspo** [girzel/org-annotate#12]
When I use "org-annotate-display-notes" the "text" column indicates [no text] even if there is text between the brackets

<img width="665" alt="Capture d’écran, le 2022-04-14 à 10 39 41" src="https://user-images.githubusercontent.com/1280210/163413989-c7aaa185-cd1e-4371-b61b-22aa2b21c273.png">

**Comment by samspo** [comment]
Sorry. It seems to work now. I suppose it was a problem in my config.

**Comment by girzel** [comment]
I'm glad this resolved itself before I actually went to look at it! :) Closing now.
