### ISSUE TITLE
comments do not export

### ISSUE THREAD

**Issue by jkitchin** [girzel/org-annotate#2]
I was trying to export an org file with some org-comments in them, and I had to do this to get it to happen:

(defun org-comment-export-comment (path desc format)
   (let ((export-func
-        (intern-soft (format "org-comment-%s-export-function" format))))
-        (symbol-value
-         (intern-soft (format "org-comment-%s-export-function" format)))))
   (if (and export-func
           (fboundp export-func))
  +
      (funcall export-func path desc)
     ;; If there's no function to handle the comment, just delete it.
     desc)))

Do your exports work?

**Comment by girzel** [comment]
Hi, I'm on the road right now with only a minimal setup, give me a few
days and I'll take a look!

**Comment by girzel** [comment]
Yup, you're quite right -- I don't know why I thought that was working before. Unwrapping a level of symbol-value is definitely necessary.

Also, I ended up renaming the whole library org-annotate, including changing the note syntax to "note:", sorry if that causes any difficulties. "Comment" just seemed like too overloaded of a term.
